// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	broker "github.com/triumphpc/go-musthave-diploma-gophermart/internal/app/pkg/broker"

	mock "github.com/stretchr/testify/mock"

	models "github.com/triumphpc/go-musthave-diploma-gophermart/internal/app/models"
)

// Publisher is an autogenerated mock type for the Publisher type
type Publisher struct {
	mock.Mock
}

// Push provides a mock function with given fields: task
func (_m *Publisher) Push(task func(chan<- models.Order) error) error {
	ret := _m.Called(task)

	var r0 error
	if rf, ok := ret.Get(0).(func(func(chan<- models.Order) error) error); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Run provides a mock function with given fields: ctx, sub
func (_m *Publisher) Run(ctx context.Context, sub broker.Subscriber) error {
	ret := _m.Called(ctx, sub)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, broker.Subscriber) error); ok {
		r0 = rf(ctx, sub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
