// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"
	order "github.com/triumphpc/go-musthave-diploma-gophermart/internal/app/models"

	mock "github.com/stretchr/testify/mock"
)

// QueueBroker is an autogenerated mock type for the QueueBroker type
type QueueBroker struct {
	mock.Mock
}

// Push provides a mock function with given fields: _a0
func (_m *QueueBroker) Push(ctx context.Context, _a0 order.Order) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(order.Order) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Run provides a mock function with given fields: ctx
func (_m *QueueBroker) Run(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
