// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Executor is an autogenerated mock type for the Executor type
type Executor struct {
	mock.Mock
}

// Pause provides a mock function with given fields: sec
func (_m *Executor) Pause(sec int) {

}

// Push provides a mock function with given fields: userID, orderCode
func (_m *Executor) Push(userID int, orderCode int) error {
	return nil
}

// Run provides a mock function with given fields: ctx
func (_m *Executor) Run(ctx context.Context) error {
	return nil
}
